name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Set up clang
      run: bash .github/scripts/setup_clang.sh

    - name: Set up deno
      run: bash .github/scripts/setup_deno.sh

    - name: Run tests
      run: deno test --unstable -A
